### ISSUE TITLE
sap_system_facts  must be run on SAP machine: undocumented, doesn't fail if not

### ISSUE THREAD

**Issue by azrdev** [sap-linuxlab/community.sap_libs#34]
### Summary

Apparently the modules can be run on any machine (e.g. `delegate_to: localhost`) except for sap_system_facts, which (according to the source) looks on the managed node it is executed on.

Furthermore, in such a case it just returns successfully without producing facts, I'd expect a task failure if there's no SAP on that host

### Issue Type

Bug Report

### Component Name

community.sap_libs.sap_system_facts

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.15.0]
```

### community.sap_libs Version

```console (paste below)
$ ansible-galaxy collection list community.sap_libs
1.4.1
```

### OS / Environment

AAP 2.4 / AAC 4.4.7

### Steps to Reproduce

```yaml (paste below)
- hosts: localhost
  gather_facts: false
  tasks:
  - community.sap_libs.sap_system_facts:
    ignore_errors: true

  - community.sap_libs.sap_system_facts:
      conn_host: sap.example.com
      conn_username: admin
      conn_password: password
```

### Expected Results

1. a task failure
2. a task success

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
