### ISSUE TITLE
sap_control_exec unsupported functions

### ISSUE THREAD

**Issue by rainerleber** [sap-linuxlab/community.sap_libs#44]
### Summary

sap_control_exec module uses the XML api. The documentation is kind of missleading as the e.g.StartWait is not available in in the wsdl output.

The supported functions are:

Start
Stop
Shutdown
InstanceStart
InstanceStop
Bootstrap
ParameterValue
GetProcessList
GetProcessList2
GetStartProfile
GetTraceFile
GetAlertTree
GetAlerts
RestartService
StopService
GetEnvironment
ListDeveloperTraces
ListLogFiles
ReadDeveloperTrace
ReadLogFile
AnalyseLogFile
ConfigureLogFileList
GetLogFileList
RestartInstance
SendSignal
GetVersionInfo
GetQueueStatistic
GetInstanceProperties
OSExecute
AnalyseLogFiles
GetAccessPointList
GetSystemInstanceList
StartSystem
StopSystem
RestartSystem
AccessCheck
GetProcessParameter
SetProcessParameter
SetProcessParameter2
ShmDetach
CreateSnapshot
ReadSnapshot
ListSnapshots
DeleteSnapshots
RequestLogonFile
GetNetworkId
GetSecNetworkId
UpdateSystem
GetSystemUpdateList
UpdateSCSInstance
ABAPReadSyslog
ABAPReadRawSyslog
ABAPGetWPTable
ABAPAcknoledgeAlerts
CMGetThreadList
ICMGetConnectionList
ICMGetCacheEntries
ICMGetProxyConnectionList
WebDispGetServerList
WebDispGetGroupList
WebDispGetVirtHostList
WebDispGeUrlPrefixList
EnqGetLockTable
EnqRemoveLocks
EnqGetStatistic

### Issue Type

Bug Report

### Component Name

sap_control_exec

### Ansible Version

```console (paste below)
$ ansible --version

```

### community.sap_libs Version

```console (paste below)
$ ansible-galaxy collection list community.sap_libs

```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### Steps to Reproduce

```yaml (paste below)
    - name: Start SAP Instance
      community.sap_libs.sap_control_exec:
        hostname: "{{ ansible_host }}"
        sysnr: "{{ instancenr }}"
        function: StartWait
        parameter: "300 2"
        username: "{{ username }}"
        password: "{{ password }}"
```

### Expected Results

Wait until started

### Actual Results

```console (paste below)
fatal: []: FAILED! => {"changed": false, "error": "Method not found: 'SAPControl.SAPControl.StartWait'", "msg": "Something went wrong connecting to the SAPCONTROL SOAP API.", "out": {}}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
