### ISSUE TITLE
sap_control_exec Windows support

### ISSUE THREAD

**Issue by ms-automatics** [sap-linuxlab/community.sap_libs#47]
### Summary

Would be great to have Windows support for several modules, e.g. for sap_control_exec in a first step. Either by directly supporting Windows within the existing module if possible or by creating separate Windows modules like sap_control_exec_win for example.

### Issue Type

Feature Idea

### Component Name

sap_control_exec

### Additional Information

```yaml (paste below)
# Either just support windows in the existing module
- name: GetProcessList with sysnr
  community.sap_libs.sap_control_exec:
    hostname: 192.168.8.15
    sysnr: "01"
    function: GetProcessList

# Or with a separate Windows module
- name: GetProcessList with sysnr
  community.sap_libs.sap_control_exec_win:
    hostname: 192.168.8.15
    sysnr: "01"
    function: GetProcessList
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
