### ISSUE TITLE
Remove Python shebang

### ISSUE THREAD

**Issue by sean-freeman** [sap-linuxlab/community.sap_libs#49]
### Summary

Remove Python shebang from all Ansible Modules, which cause errors with Python venv:
https://github.com/search?q=repo%3Asap-linuxlab%2Fcommunity.sap_libs%20%23!&type=code

See Ansible Core built-in modules for proof (shebang only exists on `hostname` Ansible Module):
https://github.com/search?q=repo%3Aansible%2Fansible+path%3A%2F%5Elib%5C%2Fansible%5C%2Fmodules%5C%2F%2F+%23%21&type=code

### Issue Type

Bug Report

### Component Name

`python`

### Ansible Version

N/A

### community.sap_libs Version

All

### Configuration

N/A

### Steps to Reproduce

N/A

### Expected Results

N/A

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by kksat** [comment]
I would like to leave it here for your information only:

https://docs.ansible.com/ansible/latest/dev_guide/testing/sanity/shebang.html

"
This does not apply to Ansible modules, which should not be executable and must always use #!/usr/bin/python.

Some exceptions are permitted. Ask if you have questions.
"

**Comment by sean-freeman** [comment]
@kksat Please read the below in full:

- https://github.com/ansible/ansible/issues/83603
- https://github.com/ansible/ansible-documentation/pull/1718

**Comment by kksat** [comment]
I read links you provided in full. Your take from the links you posted is that python shebang should be completely removed from ansible modules (as in the title of this bug)? 

My understanding is different and more close to the statement from sanity documentation that ansible python modules should always use '#!/usr/bin/python' as shebang. I would appreciate if you can elaborate on your understanding and implications you see for an ansible collection from the links you posted.

**Comment by sean-freeman** [comment]
@kksat Already tested `#!/usr/bin/python` and it still doesn't work with `auto` on https://docs.ansible.com/ansible/latest/reference_appendices/config.html#interpreter-python + using Python with `venv`.

Hence provided the Ansible built-in modules as proof of the removal.

Removing shebang has no functional impact on the Ansible Module, but does solve problems where the target (or localhost etc) that is executing the Ansible Module (Python file) is required to use a specific interpreter / venv.

Otherwise it will always attempt to use the System Python, which may be locked to a much older version and the end-user (best practice) does not wish to install additional Python Packages to the System Python; for stability and security reasons.

**Comment by marcelmamula** [comment]
Adding to this discussion: Shebang change in `sap_launchpad` https://github.com/sap-linuxlab/community.sap_launchpad/blob/dev/plugins/modules/maintenance_planner_files.py has resolved issues when trying to use venv.

Issue with python shebang:
```console
The module failed to execute correctly, you probably need to set the interpreter
"module_stdout": "/bin/sh: line 1: /usr/bin/env python3: No such file or directory
```

These were modules executed with different parameters for venv, but they did not work until I removed python shebang.
```yaml
      vars:
        ansible_python_interpreter: "{{ sap_launchpad_temp_venv.path ~ '/bin/' ~ sap_launchpad_python_interpreter }}"
      environment: 
        PATH: "{{ sap_launchpad_temp_venv.path }}/bin:{{ ansible_env.PATH }}" 
        PYTHONPATH: "{{ sap_launchpad_temp_venv.path }}/lib/{{ sap_launchpad_python }}/site-packages" 
        VIRTUAL_ENV: "{{ sap_launchpad_temp_venv.path }}"
```
